services:
  app-a:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - APP_NAME=app-a
      - APP_URL_DESTINO=http://app-b:8000
      - APP_ERRORS=5
      - APP_LATENCY=100
    networks:
      - app-network

  app-b:
    build: .
    ports:
      - "8001:8000"
      - "8081:8080"
    environment:
      - APP_NAME=app-b
      - APP_URL_DESTINO=http://app-c:8000
      - APP_ERRORS=10
      - APP_LATENCY=150
    networks:
      - app-network

  app-c:
    build: .
    ports:
      - "8002:8000"
      - "8082:8080"
    environment:
      - APP_NAME=app-c
      - APP_ERRORS=15
      - APP_LATENCY=200
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - app-network

networks:
  app-network: